### PR TITLE
Release/0.4.0

### PR DESCRIPTION
**Pull request by firemound**
@srikanchinatham I have some changes for deployment from dev to prod, but it looks like you committed changes into dev for BAYGEN-98. If these are not ready for prod, could you please remove these changes from the dev branch? Thanks.

Issues in release:
- BAYGEN-85
- BAYGEN-86
- BAYGEN-102

### CODE REVIEW

**Comment by srikanchinatham** [comment]
They can be migrated to Production

**Comment by firemound** [comment]
@srikanchinatham are you sure? Did you look at the changes? I'm not sure their right.

**Comment by srikanchinatham** [comment]
How to delete them? I am outside and can't get to computer in couple of
hours. If you can reject it then reject changes. I will create new request

**Comment by firemound** [comment]
@srikanchinatham I reversed out the changes from this branch. This shouldn't be a problem going forward since you're now using feature branches.

**Comment by firemound** [comment]
Thanks @srikanchinatham, it would be great if you could show me how you would do it differently. Maybe we'll have time on our call today. Thanks!

**Pull request closed without merging**
